// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa6roPTFD-3Vjxi8amUtz3pgYSCJzgHEU',
    appId: '1:1036388644273:web:d822e018aa632830d9f990',
    messagingSenderId: '1036388644273',
    projectId: 'monappli-f4791',
    authDomain: 'monappli-f4791.firebaseapp.com',
    storageBucket: 'monappli-f4791.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6fGvDUKLcpC8gLyHZ5DJTah6LyrA863g',
    appId: '1:1036388644273:android:8d6fedb9df382ae8d9f990',
    messagingSenderId: '1036388644273',
    projectId: 'monappli-f4791',
    storageBucket: 'monappli-f4791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7mva_mMjVHXtzJgIGGv7rVUiBOeOMyzA',
    appId: '1:1036388644273:ios:59cc7bad1524673ed9f990',
    messagingSenderId: '1036388644273',
    projectId: 'monappli-f4791',
    storageBucket: 'monappli-f4791.firebasestorage.app',
    iosClientId: '1036388644273-nt15g8opoukuh28g237a9b2kgdg35lsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.monAppli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7mva_mMjVHXtzJgIGGv7rVUiBOeOMyzA',
    appId: '1:1036388644273:ios:59cc7bad1524673ed9f990',
    messagingSenderId: '1036388644273',
    projectId: 'monappli-f4791',
    storageBucket: 'monappli-f4791.firebasestorage.app',
    iosClientId: '1036388644273-nt15g8opoukuh28g237a9b2kgdg35lsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.monAppli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa6roPTFD-3Vjxi8amUtz3pgYSCJzgHEU',
    appId: '1:1036388644273:web:ecbb5f10c3fd44ccd9f990',
    messagingSenderId: '1036388644273',
    projectId: 'monappli-f4791',
    authDomain: 'monappli-f4791.firebaseapp.com',
    storageBucket: 'monappli-f4791.firebasestorage.app',
  );

}